/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#424754",
        "surface": "#f8f9fa",
        "primary": "#0058be",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#fefcff",
        "tertiary": "#755b00",
        "tertiary-container": "#c9a84c",
        "tertiary-fixed": "#ffe08f",
        "tertiary-fixed-dim": "#e6c364",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-container": "#503d00",
        "secondary": "#5f5e5c",
        "secondary-container": "#e5e2de",
        "secondary-fixed": "#e5e2de",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1c1c1a",
        "outline": "#727785",
        "outline-variant": "#c2c6d6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#005ac2",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "sans-serif"],
        serif: ["Newsreader", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};